lr: 0.0005
momentum: 0.9
weight_decay: 0.0005
epochs: 80
warmup_epochs: 0
batch_size: 50
train_num_workers: 8
test_num_workers: 8
dataset_root: raw_data
dataset: flixster
max_neighbors: 200
max_hops: 2
cluster_sample: True
input_embedding: True
input_channels: 4
edge_classes: 10
heads: 4
layers: 4
edge_embedding: cumsum
attention: True
edge_feature: True
# Just for side information #
use_feature: False
context_dim: 4
item_num_embeddings: 3000
user_num_embeddings: 3000
# Just for side information #
is_cuda: True
gpu_ids: [0]
seed: 42
loss_mode: mse
optim_mode: Adam #Adam
lr_mode: poly #multistep
lr_step: 40
multistep_epochs: [20,20,20]
log_prefix: train