batch_size: 50
num_workers: 8
dataset_root: raw_data
pretrain_dataset: ml_100k
max_neighbors: 200
max_hops: 2
cluster_sample: True
input_embedding: True
input_channels: 4
edge_classes: 5
heads: 4
layers: 4
edge_embedding: cumsum
attention: True
edge_feature: True
checkpoint_path: log/2022-06-14-10-45-37-h=2-content-ml_100k-momentum0.9-weightdecay5e-05-lr0.0005-bs50/best_model.pth.tar
ensemble: False
ensemble_path: log/2022-06-14-10-45-37-h=2-content-ml_100k-momentum0.9-weightdecay5e-05-lr0.0005-bs50/checkpoint
douban_multiply_by: 1
flixster_multiply_by: 1
yahoo_music_multiply_by: 20
is_cuda: True
gpu_ids: [0]