batch_size: 50
num_workers: 8
dataset_root: raw_data
pretrain_dataset: ml_100k
max_neighbors: 200
input_embedding: True
input_channels: 4
edge_classes: 5
heads: 2
layers: 4
attention: True
checkpoint_path: log/2021-05-24-09-17-59-EGAT-elu-concat-self_feature-cumsum_embedding-mlp-ml_100k-momentum0.9-weightdecay5e-05-lr0.0005-bs50/best_model.pth.tar
ensemble: True
ensemble_path: log/2021-05-24-09-17-59-EGAT-elu-concat-self_feature-cumsum_embedding-mlp-ml_100k-momentum0.9-weightdecay5e-05-lr0.0005-bs50/checkpoint
douban_multiply_by: 1
flixster_multiply_by: 1
yahoo_music_multiply_by: 20
is_cuda: True
gpu_ids: [0]