lr: 0.0005
momentum: 0.9
weight_decay: 0.00005
epochs: 80 #40
warmup_epochs: 0
batch_size: 50
train_num_workers: 8
test_num_workers: 8
dataset_root: raw_data
dataset: yahoo_music
max_neighbors: 200
max_hops: 2
cluster_sample: True
input_embedding: True
input_channels: 4
edge_classes: 100
heads: 2
layers: 4
edge_embedding: cumsum
attention: True
edge_feature: True
is_cuda: True
gpu_ids: [0]
seed: 42
loss_mode: mse
optim_mode: Adam #Adam
lr_mode: poly #multistep
lr_step: 40
multistep_epochs: [20,20,20]
log_prefix: h=2-mul=0.05